# Generated by Django 3.0.4 on 2020-05-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.CharField(choices=[('Bad', 'Bad'), ('Average', 'Average'), ('Excellent', 'Excellent')], max_length=10),
        ),
    ]
